In [1]:
!pip install PyPDF2

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.6/dist-packages (1.26.0)

In [2]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.6/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from nltk) (1.10.0)

In [0]:
import PyPDF2 
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [5]:
from google.colab import files
uploaded = files.upload()

Saving resume.pdf to resume.pdf

In [0]:
import pandas as pd
import numpy as np
datafile="resume.pdf"

In [0]:
pdffile = open(datafile,'rb')

In [8]:
pdfread = PyPDF2.PdfFileReader(pdffile)
pdfread

In [0]:
# seeing the number of pages will allow us to see through all #the pages
num_pages = pdfread.numPages
count = 0
text = ""

In [0]:
num_pages = pdfread.numPages
count = 0
text = ""

In [0]:
#The while loop will read each page
while count < num_pages:
    page = pdfread.getPage(count)
    count +=1
    text += page.extractText()

In [0]:
#This if statement exists to check if the above library returned words. It's done because PyPDF2 cannot read scanned files.
if text != "":
   text = text

In [13]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [14]:
#The word_tokenize() function will break our text phrases into individual words
token = word_tokenize(text)
token

['Professional',
 'Summary',
 'Pursing',
 'Post',
 'Graduation',
 'diploma',
 'in',
 'Data',
 'science',
 'Having',
 '2',
 'years',
 'of',
 'experience',
 'in',
 'Software',
 'Industry',
 '.',
 'Worked',
 'as',
 'an',
 'Application',
 'Developer',
 'in',
 'Tata',
 'Consultancy',
 'Services',
 ',',
 'Kolkata',
 '.',
 'Participated',
 'in',
 'the',
 'International',
 'Global',
 'Datathon',
 '(',
 '2019',
 ')',
 's',
 'ext',
 'Analytics',
 'Participated',
 'in',
 'the',
 'Kaggle',
 'competitons',
 'Titatinc',
 'Machine',
 'Learning',
 'from',
 'Disaster',
 'Professional',
 'Experience',
 '2',
 'Years',
 'of',
 'IT',
 'experience',
 'in',
 'Data',
 'ware',
 'housing',
 '.',
 'Good',
 'Knowledge',
 'in',
 'Machine',
 'Learn',
 'ing',
 ',',
 'Data',
 'Mining',
 ',',
 'Statistics',
 'Hands',
 'on',
 'experience',
 'with',
 'Agile',
 'Development',
 'Model',
 'and',
 'Waterfall',
 'Model',
 '.',
 'Having',
 'good',
 'knowledge',
 'in',
 'programming',
 'in',
 'various',
 'languages',
 ',',
 'communication',
 'and',
 'interpersonal',
 'skills',
 ',',
 'active',
 'team',
 'worker',
 'and',
 'full',
 'of',
 'enterprise',
 'initiatives',
 '.',
 'Technical',
 'Skills',
 'Set',
 'Platforms',
 ':',
 'Google',
 'Clou',
 'd',
 'Platf',
 'orm',
 ',',
 'Unix',
 ',',
 'Windows',
 '.',
 'Languages',
 ':',
 'Python',
 ',',
 'R',
 ',',
 'SQL',
 'Tools',
 ':',
 'Tableau',
 'Database',
 ':',
 'O',
 'racle',
 'database',
 '11g',
 ',',
 'MySQl',
 'Others',
 ':',
 'Machine',
 'Learning',
 ',',
 'statistics',
 ',',
 'Data',
 'Mining',
 'Domain',
 ':',
 'Retail',
 'Academic',
 'Projects',
 ':',
 'Project',
 ':',
 'Breast',
 'Cancer',
 'Prediction',
 'Technolgy',
 'Used',
 ':',
 'Python',
 '(',
 'Machine',
 'Learning',
 'Algorithms',
 ')',
 'P',
 'roject',
 'Description',
 ':',
 'Built',
 'a',
 'model',
 'with',
 'good',
 'accuracy',
 'score',
 ',',
 'whether',
 'a',
 'person',
 'is',
 'effected',
 'with',
 'cancer',
 'or',
 'not',
 'Project',
 ':',
 'IMDB',
 'Recommendation',
 'System',
 'Technolgy',
 'Used',
 ':',
 'Python',
 '(',
 'Machine',
 'Learning',
 'Algorithms',
 ')',
 'P',
 'roject',
 'Description',
 ':',
 'Scrapped',
 'top',
 '250',
 'IMDB',
 'movies',
 'and',
 'build',
 'a',
 'recommendation',
 'sytem',
 'based',
 'on',
 'the',
 'plot',
 'of',
 'the',
 'movie',
 '.',
 'Project',
 ':',
 'Dashboard',
 'Creation',
 'IPL',
 'dataset',
 '(',
 '2008',
 '-',
 '2016',
 ')',
 'T',
 'echnolgy',
 'Used',
 ':',
 'Tableau',
 'P',
 'roject',
 'Description',
 ':',
 'Built',
 'a',
 'dashboard',
 'on',
 'IPL',
 'data',
 'set',
 'with',
 'he',
 'help',
 'of',
 'KPI',
 'boxes',
 ',',
 'bar',
 'graph',
 'Phanikrishna',
 'Velicheti',
 '401',
 ',',
 'G',
 '-',
 'block',
 ',',
 'Brigade',
 'Metropolis',
 ',',
 'Garudachar',
 'Palya',
 ',',
 'Mahadevapura',
 ',',
 'Bengaluru',
 ',',
 'Karnataka',
 '-',
 '560048',
 'PHONE',
 ':',
 '+91',
 '9959676104',
 'Mail',
 ':',
 'velicheti2phani',
 '@',
 'gmail.com',
 'Work',
 'History',
 'Tata',
 'Consultancy',
 'Services',
 '(',
 'O',
 'ct2016',
 'Oct2018',
 ')',
 'Project',
 ':',
 'Morrisons',
 '(',
 'Business',
 'I',
 'ntelligence',
 'Department',
 ')',
 'Technology',
 'Used',
 ':',
 'Google',
 'Cloud',
 'Platform',
 ',',
 'BigQuery',
 ',',
 'Dataflow',
 ',',
 'Pub/Sub',
 ',',
 'Project',
 'Description',
 ':',
 'Morrison',
 's',
 'is',
 'a',
 'leading',
 'chain',
 'of',
 'supermarkets',
 'in',
 'the',
 'United',
 'Kingdom',
 'and',
 'also',
 'it',
 'is',
 'trading',
 'grocery',
 'items',
 'via',
 'a',
 'web',
 'shop',
 'through',
 'Ocado',
 'M.Com',
 'grocery',
 'channel',
 'since',
 '2014',
 '.',
 'Roles',
 'and',
 'Responsibilities',
 ':',
 'Requirement',
 'analysis',
 'Application',
 'd',
 'esign',
 'and',
 'maintaining',
 'design',
 'specification',
 'and',
 'test',
 'case',
 'specification',
 'as',
 'per',
 'the',
 'new',
 'changes',
 '.',
 'Development',
 'and',
 'coding',
 'for',
 'new',
 'functionality',
 'incorporation',
 '.',
 'Analysis',
 'of',
 'codes',
 'and',
 'jobs',
 'in',
 'AWS',
 'and',
 'Google',
 'Cloud',
 'Platform',
 'to',
 'understand',
 'the',
 'new',
 'application',
 '.',
 'Internship',
 ':',
 'Kopenz',
 'Private',
 'Limited',
 ',',
 'Bombay',
 '(',
 'Inayo',
 ')',
 '(',
 'Jan',
 '2016',
 'June',
 '2016',
 ')',
 'Technology',
 'Used',
 ':',
 'Python',
 ',',
 'Django',
 'Project',
 'Description',
 ':',
 'Distribution',
 'of',
 'medicines',
 'through',
 'an',
 'app',
 'within',
 '90',
 'mins',
 'throughout',
 'the',
 'Bombay',
 'city',
 'Roles',
 'and',
 'Responsibilities',
 ':',
 'Worked',
 'as',
 'python',
 'backend',
 'developer',
 'for',
 'structuring',
 'the',
 'database',
 'using',
 'mysql',
 '.',
 'Education',
 'Post',
 '-',
 'Graduation',
 ':',
 'Pursing',
 'Post',
 'Graduation',
 'diploma',
 'in',
 'data',
 'science',
 'form',
 'Manipal',
 'ProLearn',
 '-',
 '9.125',
 '(',
 'Till',
 'date',
 ')',
 'Post',
 '-',
 'Graduation',
 ':',
 'Masters',
 'of',
 'science',
 'in',
 'IT',
 'with',
 'CGPA',
 '8.3',
 'from',
 'Jawaharlal',
 'Nehru',
 'Technological',
 'University',
 'Kakinada',
 '(',
 'JNTUK',
 ')',
 'Graduation',
 ':',
 'B.Tech',
 'with',
 '68',
 '%',
 'from',
 'Jawaharlal',
 'Nehru',
 'Technological',
 'University',
 'Hyderabad',
 '(',
 'JNTUH',
 ')',
 'XII',
 'th',
 ':',
 'Higher',
 'Se',
 'condary',
 'Education',
 'Andra',
 'Pradesh',
 '(',
 '1',
 '2',
 'th',
 'score',
 '83.5',
 '%',
 ')',
 '.',
 'X',
 'th',
 ':',
 'Secondary',
 'Education',
 '-',
 'Andra',
 'Pradesh',
 '(',
 '10',
 'th',
 'score',
 '76',
 '%',
 ')',
 '.']

In [0]:
# Now we have a text variable which contains all the text derived #from our PDF file.  print(text) to see what it contains. contains a lot of spaces, possibly junk such as '\n' etc.
# Now, we will clean our text variable, and return it as a list of keywords.

In [0]:
#The word_tokenize() function will break our text phrases into individual words
token = word_tokenize(text)

In [0]:
#we'll create a new list which contains punctuation  to clean
punctuations = ['(',')',';',':','[',']',',']

In [20]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [0]:
#We initialize the stopwords variable which has list of words like #"The", "I", "and", etc. that don't have much value as keywords
stop_words = stopwords.words('english')

In [0]:
from nltk.corpus import stopwords

In [0]:
#We create a list comprehension which only returns a list of words that are NOT IN stop_words and NOT IN punctuations.
keywords = [word for word in token if not word in stop_words and not word in punctuations]

In [24]:
keywords

['Professional',
 'Summary',
 'Pursing',
 'Post',
 'Graduation',
 'diploma',
 'Data',
 'science',
 'Having',
 '2',
 'years',
 'experience',
 'Software',
 'Industry',
 '.',
 'Worked',
 'Application',
 'Developer',
 'Tata',
 'Consultancy',
 'Services',
 'Kolkata',
 '.',
 'Participated',
 'International',
 'Global',
 'Datathon',
 '2019',
 'ext',
 'Analytics',
 'Participated',
 'Kaggle',
 'competitons',
 'Titatinc',
 'Machine',
 'Learning',
 'Disaster',
 'Professional',
 'Experience',
 '2',
 'Years',
 'IT',
 'experience',
 'Data',
 'ware',
 'housing',
 '.',
 'Good',
 'Knowledge',
 'Machine',
 'Learn',
 'ing',
 'Data',
 'Mining',
 'Statistics',
 'Hands',
 'experience',
 'Agile',
 'Development',
 'Model',
 'Waterfall',
 'Model',
 '.',
 'Having',
 'good',
 'knowledge',
 'programming',
 'various',
 'languages',
 'communication',
 'interpersonal',
 'skills',
 'active',
 'team',
 'worker',
 'full',
 'enterprise',
 'initiatives',
 '.',
 'Technical',
 'Skills',
 'Set',
 'Platforms',
 'Google',
 'Clou',
 'Platf',
 'orm',
 'Unix',
 'Windows',
 '.',
 'Languages',
 'Python',
 'R',
 'SQL',
 'Tools',
 'Tableau',
 'Database',
 'O',
 'racle',
 'database',
 '11g',
 'MySQl',
 'Others',
 'Machine',
 'Learning',
 'statistics',
 'Data',
 'Mining',
 'Domain',
 'Retail',
 'Academic',
 'Projects',
 'Project',
 'Breast',
 'Cancer',
 'Prediction',
 'Technolgy',
 'Used',
 'Python',
 'Machine',
 'Learning',
 'Algorithms',
 'P',
 'roject',
 'Description',
 'Built',
 'model',
 'good',
 'accuracy',
 'score',
 'whether',
 'person',
 'effected',
 'cancer',
 'Project',
 'IMDB',
 'Recommendation',
 'System',
 'Technolgy',
 'Used',
 'Python',
 'Machine',
 'Learning',
 'Algorithms',
 'P',
 'roject',
 'Description',
 'Scrapped',
 'top',
 '250',
 'IMDB',
 'movies',
 'build',
 'recommendation',
 'sytem',
 'based',
 'plot',
 'movie',
 '.',
 'Project',
 'Dashboard',
 'Creation',
 'IPL',
 'dataset',
 '2008',
 '-',
 '2016',
 'T',
 'echnolgy',
 'Used',
 'Tableau',
 'P',
 'roject',
 'Description',
 'Built',
 'dashboard',
 'IPL',
 'data',
 'set',
 'help',
 'KPI',
 'boxes',
 'bar',
 'graph',
 'Phanikrishna',
 'Velicheti',
 '401',
 'G',
 '-',
 'block',
 'Brigade',
 'Metropolis',
 'Garudachar',
 'Palya',
 'Mahadevapura',
 'Bengaluru',
 'Karnataka',
 '-',
 '560048',
 'PHONE',
 '+91',
 '9959676104',
 'Mail',
 'velicheti2phani',
 '@',
 'gmail.com',
 'Work',
 'History',
 'Tata',
 'Consultancy',
 'Services',
 'O',
 'ct2016',
 'Oct2018',
 'Project',
 'Morrisons',
 'Business',
 'I',
 'ntelligence',
 'Department',
 'Technology',
 'Used',
 'Google',
 'Cloud',
 'Platform',
 'BigQuery',
 'Dataflow',
 'Pub/Sub',
 'Project',
 'Description',
 'Morrison',
 'leading',
 'chain',
 'supermarkets',
 'United',
 'Kingdom',
 'also',
 'trading',
 'grocery',
 'items',
 'via',
 'web',
 'shop',
 'Ocado',
 'M.Com',
 'grocery',
 'channel',
 'since',
 '2014',
 '.',
 'Roles',
 'Responsibilities',
 'Requirement',
 'analysis',
 'Application',
 'esign',
 'maintaining',
 'design',
 'specification',
 'test',
 'case',
 'specification',
 'per',
 'new',
 'changes',
 '.',
 'Development',
 'coding',
 'new',
 'functionality',
 'incorporation',
 '.',
 'Analysis',
 'codes',
 'jobs',
 'AWS',
 'Google',
 'Cloud',
 'Platform',
 'understand',
 'new',
 'application',
 '.',
 'Internship',
 'Kopenz',
 'Private',
 'Limited',
 'Bombay',
 'Inayo',
 'Jan',
 '2016',
 'June',
 '2016',
 'Technology',
 'Used',
 'Python',
 'Django',
 'Project',
 'Description',
 'Distribution',
 'medicines',
 'app',
 'within',
 '90',
 'mins',
 'throughout',
 'Bombay',
 'city',
 'Roles',
 'Responsibilities',
 'Worked',
 'python',
 'backend',
 'developer',
 'structuring',
 'database',
 'using',
 'mysql',
 '.',
 'Education',
 'Post',
 '-',
 'Graduation',
 'Pursing',
 'Post',
 'Graduation',
 'diploma',
 'data',
 'science',
 'form',
 'Manipal',
 'ProLearn',
 '-',
 '9.125',
 'Till',
 'date',
 'Post',
 '-',
 'Graduation',
 'Masters',
 'science',
 'IT',
 'CGPA',
 '8.3',
 'Jawaharlal',
 'Nehru',
 'Technological',
 'University',
 'Kakinada',
 'JNTUK',
 'Graduation',
 'B.Tech',
 '68',
 '%',
 'Jawaharlal',
 'Nehru',
 'Technological',
 'University',
 'Hyderabad',
 'JNTUH',
 'XII',
 'th',
 'Higher',
 'Se',
 'condary',
 'Education',
 'Andra',
 'Pradesh',
 '1',
 '2',
 'th',
 'score',
 '83.5',
 '%',
 '.',
 'X',
 'th',
 'Secondary',
 'Education',
 '-',
 'Andra',
 'Pradesh',
 '10',
 'th',
 'score',
 '76',
 '%',
 '.']

In [0]:
import re

In [0]:
#particularly I want an email from the resume
emails = re.findall(r"[a-z0-9\.\-+]+@[a-z0-9\.\-+]+\.[a-z]+", text)

In [27]:
emails

['velicheti2phani@gmail.com']

In [0]:
pdfFileObj = open('resume.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

#print(pdfReader.numPages)

pageObj1 = pdfReader.getPage(0)
pagecontent = pageObj1.extractText()
temp = []

def between(value, a, b):
    # Find and validate before-part.
    pos_a = value.find(a)
    if pos_a == -1: return ""
    # Find and validate after part.
    pos_b = value.rfind(b)
    if pos_b == -1: return ""
    # Return middle part.
    adjusted_pos_a = pos_a + len(a)
    if adjusted_pos_a >= pos_b: return ""
    return value[adjusted_pos_a:pos_b]

desired = between(pagecontent,"initiatives.","Academic")
temp = between(pagecontent,"initiatives.","Academic")

In [41]:
temp = [k for k in temp.split('\n') if len(k)>2]
print(temp)

['Technical Skills Set', 'Platforms', ': Google Clou', 'd Platf', 'orm, Unix, Windows', 'Languages ', 'Python,', 'SQL', 'Tools', 'Tableau', 'Database', ': O', 'racle database 11g, MySQl', 'Others: ', 'Machine Learning ,statistics,Data Mining', 'Domain: ', 'Retail']

In [0]:
#Calculating Weightage
#TF: Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization:
#TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document).

#IDF: Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following:
#IDF(t) = log_e(Total number of documents / Number of documents with term t in it).

In [0]:
from gensim.summarization import keywords
import warnings
warnings.filterwarnings("ignore")

In [0]:
values = keywords(text=text,split='\n',scores=True)

In [39]:
data = pd.DataFrame(values,columns=['keyword','score'])
data = data.sort_values('score',ascending=False)
data.head(10)

          keyword     score
0        projects  0.241617
1         project  0.241617
2            data  0.171524
3     description  0.169763
4       education  0.163987
5      graduation  0.145214
6         grocery  0.138845
7       developer  0.133075
8     development  0.133075
10  technological  0.127024